# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tsouhaieb blog
email: tarhounisouhaieb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is my blog, where i post things that i want to remember,.



#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "http://tsouhaieb.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: tsouhaieb
copyright:
   name: tsouhaieb
   link: 'http://tsouhaieb.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname:  tsouhaieb

#social
facebook: http://facebook.com/tsouhaieb
quora: http://quora.com/tsouhaieb
twitter: http://twitter.com/tsouhaieb
github: http://github.com/tsouhaieb

#facebook like box
fb-app-id: 453662465005663
fb-page-url: https://www.facebook.com/Tsouhaieb-152671415294371/
fb-page-title: Tsouhaieb

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
